[package]
name = "crustty"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glium = "0.32.0"
glutin = "0.29.1"
nix = "0.23.0"
rusttype ={ version = "0.9.3", features = ["gpu_cache"] }
